import 'package:fpdart/fpdart.dart';
import 'package:injectable/injectable.dart';
import 'package:gsports/core/error/failures.dart';
import 'package:gsports/core/usecases/usecase.dart';
import 'package:gsports/features/booking/domain/repositories/booking_repository.dart';
import '../entities/transaction_entity.dart';
import '../repositories/transaction_repository.dart';

@lazySingleton
class SyncWalletTransactions implements UseCase<void, String> {
  final BookingRepository bookingRepository;
  final TransactionRepository transactionRepository;

  SyncWalletTransactions(this.bookingRepository, this.transactionRepository);

  @override
  Future<Either<Failure, void>> call(String userId) async {
    // 1. Fetch Partner Bookings (Paid only)
    final bookingsResult = await bookingRepository.getPartnerBookings(userId);

    return await bookingsResult.fold((failure) => Left(failure), (
      bookings,
    ) async {
      final paidBookings = bookings
          .where(
            (b) =>
                b.paymentStatus == 'paid' ||
                b.paymentStatus == 'settlement' ||
                b.paymentStatus == 'capture',
          )
          .toList();

      if (paidBookings.isEmpty) return const Right(null);

      // 2. Fetch existing transactions
      final txResult = await transactionRepository.getTransactionsByUserId(
        userId,
      );

      return await txResult.fold((failure) => Left(failure), (
        transactions,
      ) async {
        final existingReferenceIds = transactions
            .where((t) => t.type == 'revenue')
            .map((t) => t.referenceId)
            .toSet();

        for (final booking in paidBookings) {
          if (!existingReferenceIds.contains(booking.id)) {
            // Missing transaction! Create it.
            if (booking.netRevenue != null && booking.netRevenue! > 0) {
              final transaction = TransactionEntity(
                id: '', // Generated by Firestore
                userId: userId,
                type: 'revenue',
                amount: booking.netRevenue!,
                status: 'completed',
                referenceId: booking.id,
                description:
                    'Revenue from booking ${booking.venueName ?? ''} - ${booking.courtName ?? ''}',
                createdAt: booking.createdAt,
              );
              await transactionRepository.createTransaction(transaction);
            }
          }
        }
        return const Right(null);
      });
    });
  }
}
